apiVersion: apps/v1
kind: Deployment
metadata:
  name: customercenter bc
  labels:
    app: customercenter bc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customercenter bc
  template:
    metadata:
      labels:
        app: customercenter bc
    spec:
      containers:
        - name: customercenter bc
          image: "username/customercenter bc:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
